training:
  batch_size: 128
  n_epochs: 3000
  n_iters: 100000
  algo: "ssm"

data:
  dataset: "CIFAR10"
  image_size: 64
  channels: 3

model:
  n_particles: 1
  lam: 10
  z_dim: 16
  eps_dim: 16
  nef: 32
  ndf: 32

optim:
  weight_decay: 0.000
  optimizer: "RMSProp"
  lr: 0.0001